server:
  port: 5001

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
        - id: server
          uri: lb://server
          predicates:
            - Path=/server/**
          filters:
            - StripPrefix=1
        - id: client
          uri: lb://client
#          多个规则时，默认是and并集条件
          predicates:
            - Path=/client1/**
            - Path=/client1/inner/**
          filters:
            - StripPrefix=1
